"""empty message

Revision ID: 28dbb2dae8
Revises: None
Create Date: 2015-12-16 23:13:40.079479

"""

# revision identifiers, used by Alembic.
revision = '28dbb2dae8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
