"""empty message

Revision ID: 6e41c5ca0f
Revises: None
Create Date: 2015-12-13 23:17:03.902868

"""

# revision identifiers, used by Alembic.
revision = '6e41c5ca0f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
